spring:
  application:
    index: ${random.uuid}
  cloud:
    bus:
      destination: spring-cloud-bus-test
    stream:
      binder:
        zkNodes: localhost:2181
        brokers: localhost:9092
        zkSessionTimeout: 6000