spring:
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      group-id: baeldung
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

test:
  topic: embedded-test-topic

