spring:
  cloud:
    stream:
      function:
        definition: send;sendFlux;accumulate;receive
      bindings:
        send-out-0:
          destination: ints
        sendFlux-out-0:
          destination: ints
        accumulate-in-0:
          destination: ints
        accumulate-out-0:
          destination: total
        receive-in-0:
          destination: total

